# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build

language: node_js
node_js:
  - 12

services:
  - docker

before_script:
  - echo "tests:"
  - echo "none "

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy edwinjay/udagram-reverseproxy:latest
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user edwinjay/udagram-api-user:latest
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed edwinjay/udagram-api-feed:latest
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend edwinjay/udagram-frontend:latest
  - docker build -t udagram-api-feed ./udagram-api-feed
# Tasks to perform after the process is successful.
after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push edwinjay/udagram-api-feed:latest
  - docker push edwinjay/udagram-api-user:latest
  - docker push edwinjay/udagram-frontend:latest
  - docker push edwinjay/udagram-reverseproxy:latest